# Generated by Django 5.1.3 on 2024-12-02 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0002_representativerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='representative',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='representative', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
