# Generated by Django 5.1.3 on 2024-12-04 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0003_representative_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='representative',
            name='user',
        ),
        migrations.CreateModel(
            name='TournamentWinner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('sport', models.CharField(choices=[('football', 'Football'), ('cricket', 'Cricket'), ('chess', 'Chess'), ('handball', 'Handball'), ('carom', 'Carom')], max_length=50)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.team')),
            ],
            options={
                'unique_together': {('year', 'sport')},
            },
        ),
    ]
